command: ["npm", "start"]
port: 3000
timeout: 300

env:
  - name: CLIENT_ID
    value: "${CLIENT_ID}"

  - name: TEST_SECRET
    value: "${TEST_SECRET}"

  - name: DATABRICKS_HOST
    value: "${DATABRICKS_HOST}"

  - name: DATABRICKS_PATH
    value: "${DATABRICKS_PATH}"
    
  - name: DATABRICKS_PAT
    value: "dapi91c7e7ca702f7358c908deb98f6656ac"
